name: Generate Pages and Deploy to GitHub Pages

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
  
        - name: Install dependencies
          run: |
              echo "----INSTALL DEPENDENCIES------"
              python -m pip install --upgrade pip
              pip install -r requirements.txt
  
        - name: Set python path and test with unittest
          run: |
              echo "----PYTHONPATH------"
              PWD=$(pwd)
              export PYTHONPATH=$PWD/src:$PWD/tests:$PWD/utils:$PYTHONPATH
              echo "PYTHONPATH=$PYTHONPATH"
              python -m unittest
  
        - name: Run script #run main.py
          run: |
              echo "---RUN MAIN SCRIPT---"
              echo "Setting PYTHONPATH"
              PWD=$(pwd)
              export PYTHONPATH=$PWD/src:$PWD/tests:$PWD/utils:$PYTHONPATH
              python src/main.py --force-rebuild --verbose
  
    deploy:
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Setup Pages
          uses: actions/configure-pages@v3
  
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
          with:
            # Upload entire repository
            path:
                "pages"
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy
          with:
            # GitHub token
            token: ${{ secrets.GITHUB_TOKEN }}
            # Target repository
            repository: ${{ github.repository }}
            # Target branch
            branch: main
            # Folder to deploy
            folder: pages
            # Commit message
            commit_message: Deploy ${{ github.sha }}
            # Commit author name
            commit_author: ${{ github.actor }}
            # Commit author email
            commit_email: ${{ github.actor }}@users.noreply.github.com
            # Force push to the target branch
            force: true